apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: srv
  namespace: rook
spec:
  replicated:
    size: 3

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: srv-pool
   namespace: rook
provisioner: rook.io/block
parameters:
  pool: srv
