apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: false
    useAllDevices: false
    storeConfig:
      storeType: bluestore
      databaseSizeMB: 1024 
      journalSizeMB: 1024  
    directories:
    - path: "/mnt/a"
    - path: "/mnt/b"
    - path: "/mnt/c"
    nodes:
    - name: "nodenuvem1"
    - name: "nodenuvem2"
    - name: "nodenuvem3"


